const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const uuidv4 = () => crypto.randomUUID();
const SuratModel = require('../models/SuratModel');
const GDriveDocModel = require('../models/GDriveDocModel');
const DisposisiModel = require('../models/DisposisiModel');
const MahasiswaModel = require('../models/MahasiswaModel');
const DosenModel = require('../models/DosenModel');
const PlottingModel = require('../models/PlottingModel');
const JadwalUjianModel = require('../models/JadwalUjianModel');
const JudulTaModel = require('../models/JudulTaModel');
const gdriveService = require('../services/GDriveStorageService');
const appConfig = require('../../config/app');
const db = require('../../config/database');

class MahasiswaController {
    static async dashboard(req, res) {
        try {
            const user = req.session.user;
            let mhs = await MahasiswaModel.findByUserId(user.id);
            if (!mhs) {
                const allMhs = await MahasiswaModel.getAll();
                mhs = (allMhs && allMhs.length > 0) ? allMhs[0] : { id: 1, nim: '21081010001', nama_lengkap: user.username, angkatan: 2021 };
            }

            const listSurat = await SuratModel.getByMahasiswaId(mhs.id);
            const plotting = await PlottingModel.getByMahasiswaId(mhs.id);

            return res.render('mahasiswa/dashboard', {
                title: 'Dashboard Mahasiswa - E-Surat TA',
                user,
                mhs,
                listSurat,
                plotting
            });
        } catch (err) {
            console.error('Mahasiswa dashboard error:', err);
            return res.status(500).send('Internal Server Error');
        }
    }

    static async renderDaftarSurat(req, res) {
        try {
            const user = req.session.user;
            let mhs = await MahasiswaModel.findByUserId(user.id);
            if (!mhs) {
                const allMhs = await MahasiswaModel.getAll();
                mhs = (allMhs && allMhs.length > 0) ? allMhs[0] : { id: 1, nim: '22650025', nama_lengkap: user.username, angkatan: 2022 };
            }

            const listSurat = await SuratModel.getByMahasiswaId(mhs.id);

            return res.render('mahasiswa/daftar_surat', {
                title: 'Daftar Surat & SK Saya - E-Surat TA',
                user,
                mhs,
                listSurat,
                error: req.query.error || null,
                success: req.query.success || null
            });
        } catch (err) {
            console.error('Mahasiswa daftar surat error:', err);
            return res.status(500).send('Internal Server Error');
        }
    }

    static async renderBuatSurat(req, res) {
        try {
            const allJenis = await SuratModel.getJenisSuratList();
            // Filter out Berita Acara Ujian (BA-UJIAN) so students cannot request it directly.
            // Berita Acara is automatically generated by Staff TU upon setting exam schedules.
            const jenisList = (allJenis || []).filter(j => 
                j.kode_surat !== 'BA-UJIAN' && 
                !j.nama_surat.toLowerCase().includes('berita acara')
            );

            const user = req.session.user;
            let mhs = await MahasiswaModel.findByUserId(user.id);
            if (!mhs) {
                const allMhs = await MahasiswaModel.getAll();
                mhs = (allMhs && allMhs.length > 0) ? allMhs[0] : { id: 1, nim: '22650025', nama_lengkap: user.username, angkatan: 2022, judul_ta: '-' };
            }

            const proposals = await JudulTaModel.getByMahasiswaId(mhs.id);
            const approvedProposal = (proposals && proposals.length > 0) ? proposals.find(p => p.status === 'diterima') : null;
            if (approvedProposal && approvedProposal.judul_ta) {
                mhs.judul_ta = approvedProposal.judul_ta;
            }

            return res.render('mahasiswa/buat_surat', {
                title: 'Pengajuan Surat Baru - E-Surat TA',
                user,
                mhs,
                approvedProposal,
                jenisList,
                error: req.query.error || null,
                success: req.query.success || null
            });
        } catch (err) {
            console.error('Buat surat render error:', err);
            return res.status(500).send('Internal Server Error');
        }
    }

    static async submitSurat(req, res) {
        try {
            const DosenModel = require('../models/DosenModel');
            const user = req.session.user;
            const mhs = await MahasiswaModel.findByUserId(user.id);
            if (!mhs) {
                return res.status(400).send('Profil mahasiswa tidak valid.');
            }

            let { jenis_surat_id, perihal, ...dataDinamis } = req.body;
            const fileUpload = req.file;
            const uuidSurat = uuidv4();

            const jenisSuratObj = await SuratModel.getJenisSuratById(jenis_surat_id);
            if (!perihal || perihal.trim() === '') {
                perihal = jenisSuratObj ? jenisSuratObj.nama_surat : 'Pengajuan Surat Administrasi TA';
            }

            // Fetch student's approved title proposal & assigned advisors
            const approvedProposal = await db.get("SELECT * FROM pengajuan_judul_ta WHERE mahasiswa_id = ? AND status = 'diterima' ORDER BY id DESC LIMIT 1", [mhs.id]);
            const plotting = await db.get("SELECT * FROM plotting_tugas_akhir WHERE mahasiswa_id = ? ORDER BY id DESC LIMIT 1", [mhs.id]);

            const p1Id = approvedProposal ? approvedProposal.dosen_pembimbing_1_id : (plotting ? plotting.dosen_pembimbing_1_id : null);
            const p2Id = approvedProposal ? approvedProposal.dosen_pembimbing_2_id : (plotting ? plotting.dosen_pembimbing_2_id : null);
            const approvedTitle = (approvedProposal && approvedProposal.judul_ta) ? approvedProposal.judul_ta : (mhs.judul_ta || '-');

            const p1Dosen = p1Id ? await DosenModel.findById(p1Id) : null;
            const p2Dosen = p2Id ? await DosenModel.findById(p2Id) : null;

            const isKartuBimbingan = jenisSuratObj && (jenisSuratObj.kode_surat === 'KARTU-BIMBINGAN' || jenisSuratObj.template_path === 'kartu_bimbingan');
            const isBaUjian = jenisSuratObj && (jenisSuratObj.kode_surat === 'BA-UJIAN' || jenisSuratObj.template_path === 'berita_acara_ujian');
            const isPersetujuanWaktu = jenisSuratObj && (jenisSuratObj.kode_surat === 'LMBR-PERSETUJUAN-WKT' || jenisSuratObj.template_path === 'lembar_persetujuan_waktu');
            const isAutoApproved = isKartuBimbingan || isBaUjian || isPersetujuanWaktu;

            // --- KHUSUS KARTU BIMBINGAN TA: BUAT 2 DOKUMEN TERPISAH (PEMBIMBING 1 & PEMBIMBING 2) ---
            if (isKartuBimbingan) {
                const crypto = require('crypto');

                // 1. Kartu Bimbingan Pembimbing 1
                const uuid1 = uuidv4();
                const hash1 = crypto.createHash('sha256').update(`${uuid1}_AUTO_APPROVED_P1_${Date.now()}`).digest('hex');
                const dinamisP1 = {
                    ...dataDinamis,
                    pembimbing_role: 1,
                    pembimbing_id: p1Id,
                    pembimbing_nama: p1Dosen ? p1Dosen.nama_dosen : 'Dosen Pembimbing 1',
                    pembimbing_1_id: p1Id,
                    pembimbing_2_id: p2Id,
                    pembimbing_1_nama: p1Dosen ? p1Dosen.nama_dosen : 'Dosen Pembimbing 1',
                    pembimbing_2_nama: p2Dosen ? p2Dosen.nama_dosen : 'Dosen Pembimbing 2',
                    judul_ta: approvedTitle
                };

                const pengajuanP1 = await SuratModel.createPengajuan({
                    uuid_surat: uuid1,
                    mahasiswa_id: mhs.id,
                    jenis_surat_id: parseInt(jenis_surat_id, 10),
                    perihal: `Kartu Bimbingan TA - Pembimbing 1 (${p1Dosen ? p1Dosen.nama_dosen : 'Utama'})`,
                    data_dinamis: dinamisP1,
                    status: 'selesai'
                });

                await db.run('UPDATE pengajuan_surat SET status = ?, qr_signature_hash = ? WHERE id = ?', [
                    'selesai',
                    hash1,
                    pengajuanP1.id
                ]);

                await DisposisiModel.addLog({
                    pengajuan_surat_id: pengajuanP1.id,
                    actor_user_id: user.id,
                    actor_role: 'mahasiswa',
                    status_sebelumnya: 'draft',
                    status_sesudahnya: 'selesai',
                    catatan_revisi: 'Dokumen Kartu Bimbingan Pembimbing 1 otomatis diterbitkan oleh Sistem.'
                });

                // 2. Kartu Bimbingan Pembimbing 2
                const uuid2 = uuidv4();
                const hash2 = crypto.createHash('sha256').update(`${uuid2}_AUTO_APPROVED_P2_${Date.now()}`).digest('hex');
                const dinamisP2 = {
                    ...dataDinamis,
                    pembimbing_role: 2,
                    pembimbing_id: p2Id,
                    pembimbing_nama: p2Dosen ? p2Dosen.nama_dosen : 'Dosen Pembimbing 2',
                    pembimbing_1_id: p1Id,
                    pembimbing_2_id: p2Id,
                    pembimbing_1_nama: p1Dosen ? p1Dosen.nama_dosen : 'Dosen Pembimbing 1',
                    pembimbing_2_nama: p2Dosen ? p2Dosen.nama_dosen : 'Dosen Pembimbing 2',
                    judul_ta: approvedTitle
                };

                const pengajuanP2 = await SuratModel.createPengajuan({
                    uuid_surat: uuid2,
                    mahasiswa_id: mhs.id,
                    jenis_surat_id: parseInt(jenis_surat_id, 10),
                    perihal: `Kartu Bimbingan TA - Pembimbing 2 (${p2Dosen ? p2Dosen.nama_dosen : 'Pendamping'})`,
                    data_dinamis: dinamisP2,
                    status: 'selesai'
                });

                await db.run('UPDATE pengajuan_surat SET status = ?, qr_signature_hash = ? WHERE id = ?', [
                    'selesai',
                    hash2,
                    pengajuanP2.id
                ]);

                await DisposisiModel.addLog({
                    pengajuan_surat_id: pengajuanP2.id,
                    actor_user_id: user.id,
                    actor_role: 'mahasiswa',
                    status_sebelumnya: 'draft',
                    status_sesudahnya: 'selesai',
                    catatan_revisi: 'Dokumen Kartu Bimbingan Pembimbing 2 otomatis diterbitkan oleh Sistem.'
                });

                return res.redirect('/mahasiswa/daftar-surat?success=' + encodeURIComponent('2 Berkas Kartu Bimbingan TA (Pembimbing 1 & Pembimbing 2) berhasil langsung diterbitkan secara otomatis! Anda dapat melihat / cetak PDF kedua kartu pada daftar surat.'));
            }

            // Sisipkan data_dinamis pembimbing & judul_ta dari approved proposal untuk dokumen lain
            dataDinamis = {
                ...dataDinamis,
                pembimbing_1_id: p1Id,
                pembimbing_2_id: p2Id,
                pembimbing_1_nama: p1Dosen ? p1Dosen.nama_dosen : '',
                pembimbing_2_nama: p2Dosen ? p2Dosen.nama_dosen : '',
                judul_ta: approvedTitle
            };

            let initialStatus = 'pending_tu';
            if (isAutoApproved) {
                initialStatus = 'selesai';
            }

            // 1. Simpan Transaksi Pengajuan Surat di DB
            const pengajuan = await SuratModel.createPengajuan({
                uuid_surat: uuidSurat,
                mahasiswa_id: mhs.id,
                jenis_surat_id: parseInt(jenis_surat_id, 10),
                perihal,
                data_dinamis: dataDinamis,
                status: initialStatus
            });

            if (isAutoApproved) {
                const crypto = require('crypto');
                const signatureHash = crypto.createHash('sha256').update(`${uuidSurat}_AUTO_APPROVED_${Date.now()}`).digest('hex');
                await db.run('UPDATE pengajuan_surat SET status = ?, qr_signature_hash = ? WHERE id = ?', [
                    'selesai',
                    signatureHash,
                    pengajuan.id
                ]);
            }

            // 2. Direct Stream Upload ke Google Drive (Subfolder Jenis Surat & Nama Pemohon)
            if (fileUpload) {
                const ROOT_FOLDER = appConfig.gdriveRootFolderId || '1jjZFf0vgrWso96dfHe2IMzf2HTzybq_1';
                const jenisFolderName = jenisSuratObj ? jenisSuratObj.nama_surat.replace(/[\/\\:*?"<>|]/g, '_') : 'Surat_Administrasi';
                const jenisFolderId = await gdriveService.getOrCreateFolder(jenisFolderName, ROOT_FOLDER);

                const mhsFolderName = `${mhs.nim}_${mhs.nama_lengkap.replace(/\s+/g, '_')}`;
                const mhsFolderId = await gdriveService.getOrCreateFolder(mhsFolderName, jenisFolderId);

                const driveResult = await gdriveService.uploadFileStream(
                    fileUpload.buffer,
                    fileUpload.originalname,
                    fileUpload.mimetype,
                    mhsFolderId
                );

                // 3. Simpan Metadata GDrive ke SQL
                await GDriveDocModel.saveMetadata({
                    pengajuan_surat_id: pengajuan.id,
                    gdrive_file_id: driveResult.id,
                    gdrive_folder_id: mhsFolderId,
                    nama_file_original: fileUpload.originalname,
                    kategori_berkas: 'syarat_lampiran',
                    mime_type: fileUpload.mimetype,
                    file_size_bytes: driveResult.size || fileUpload.size,
                    web_view_link: driveResult.webViewLink,
                    web_content_link: driveResult.webContentLink
                });
            }

            // 4. Catat Log Disposisi
            await DisposisiModel.addLog({
                pengajuan_surat_id: pengajuan.id,
                actor_user_id: user.id,
                actor_role: 'mahasiswa',
                status_sebelumnya: 'draft',
                status_sesudahnya: initialStatus,
                catatan_revisi: isAutoApproved 
                    ? 'Dokumen otomatis diterbitkan oleh Sistem (Tanpa Nomor Surat & Tanpa Verifikasi Admin).'
                    : 'Pengajuan surat baru diajukan oleh Mahasiswa.'
            });

            if (isAutoApproved) {
                return res.redirect('/mahasiswa/daftar-surat?success=' + encodeURIComponent(`Dokumen "${jenisSuratObj ? jenisSuratObj.nama_surat : 'Surat'}" berhasil langsung diterbitkan secara otomatis! Anda dapat melihat / cetak dokumen pada daftar surat.`));
            } else {
                return res.redirect('/mahasiswa/buat-surat?success=' + encodeURIComponent('Pengajuan Surat / SK berhasil dikirim! Menunggu pemeriksaan dan persetujuan (ACC) dari Admin / Staff TU.'));
            }
        } catch (err) {
            console.error('Submit surat error:', err);
            const jenisList = await SuratModel.getJenisSuratList();
            return res.render('mahasiswa/buat_surat', {
                title: 'Pengajuan Surat Baru',
                user: req.session.user,
                mhs: await MahasiswaModel.findByUserId(req.session.user.id),
                jenisList,
                error: 'Gagal mengajukan surat: ' + err.message
            });
        }
    }

    static async detailSurat(req, res) {
        try {
            const user = req.session.user;
            if (user && user.role === 'mahasiswa') {
                return res.redirect('/mahasiswa/daftar-surat');
            }

            const { id } = req.params;
            const pengajuan = await SuratModel.getDetailById(id);
            if (!pengajuan) {
                return res.status(404).send('Pengajuan surat tidak ditemukan.');
            }

            const docs = await GDriveDocModel.getBySuratId(id);
            const riwayat = await DisposisiModel.getBySuratId(id);

            return res.render('mahasiswa/detail_surat', {
                title: 'Detail Pengajuan Surat',
                user,
                pengajuan,
                docs,
                riwayat
            });
        } catch (err) {
            console.error('Detail surat error:', err);
            return res.status(500).send('Internal Server Error');
        }
    }

    static async renderJadwalUjian(req, res) {
        try {
            const user = req.session.user;
            const { filter_tanggal } = req.query;
            let listJadwal = [];
            let mhs = null;

            if (user && user.role === 'dosen') {
                const dosen = await DosenModel.findByUserId(user.id);
                if (dosen) {
                    listJadwal = await JadwalUjianModel.getByDosenId(dosen.id);
                } else {
                    listJadwal = await JadwalUjianModel.getAllJadwal();
                }
            } else {
                mhs = await MahasiswaModel.findByUserId(user.id);
                if (!mhs) {
                    const allMhs = await MahasiswaModel.getAll();
                    mhs = (allMhs && allMhs.length > 0) ? allMhs[0] : { id: 1, nim: '21081010001', nama_lengkap: user.username, angkatan: 2021 };
                }
                listJadwal = await JadwalUjianModel.getByMahasiswaId(mhs.id);
            }

            // Enrich listJadwal with formatted Hari/Tanggal, Waktu, Tempat, and Pembimbing from data_dinamis / plotting
            for (const j of listJadwal || []) {
                let dinamisObj = {};
                try {
                    dinamisObj = typeof j.data_dinamis === 'string' ? JSON.parse(j.data_dinamis) : (j.data_dinamis || {});
                } catch (e) {}

                // Resolve Pembimbing Names from data_dinamis or plotting_tugas_akhir if missing
                if (!j.p1_nama && dinamisObj.pembimbing_1_nama) j.p1_nama = dinamisObj.pembimbing_1_nama;
                if (!j.p2_nama && dinamisObj.pembimbing_2_nama) j.p2_nama = dinamisObj.pembimbing_2_nama;

                if (!j.p1_nama || !j.p2_nama) {
                    const db = require('../../config/database');
                    const plot = await db.get(`
                        SELECT d1.nama_dosen AS p1_nama, d2.nama_dosen AS p2_nama
                        FROM plotting_tugas_akhir plt
                        LEFT JOIN dosen d1 ON plt.dosen_pembimbing_1_id = d1.id
                        LEFT JOIN dosen d2 ON plt.dosen_pembimbing_2_id = d2.id
                        WHERE plt.mahasiswa_id = ?
                    `, [j.mahasiswa_id]);
                    if (plot) {
                        if (!j.p1_nama && plot.p1_nama) j.p1_nama = plot.p1_nama;
                        if (!j.p2_nama && plot.p2_nama) j.p2_nama = plot.p2_nama;
                    }
                }

                // 1. Tanggal Ujian / Hari Tanggal Display
                if (dinamisObj.hari_tanggal && dinamisObj.hari_tanggal.trim() !== '') {
                    let formatted = dinamisObj.hari_tanggal.trim();
                    // Capitalize each word e.g. "sabtu 6 agustus 2026" -> "Sabtu 6 Agustus 2026"
                    formatted = formatted.replace(/\s+/g, ' ').replace(/\b[a-z]/g, l => l.toUpperCase());
                    // Add comma after day name if missing
                    formatted = formatted.replace(/^(Senin|Selasa|Rabu|Kamis|Jumat|Jum'at|Sabtu|Minggu)\s+/i, '$1, ');
                    j.tanggal_display = formatted;
                } else if (j.tanggal_ujian) {
                    try {
                        const d = new Date(j.tanggal_ujian);
                        j.tanggal_display = d.toLocaleDateString('id-ID', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' });
                    } catch (e) {
                        j.tanggal_display = j.tanggal_ujian;
                    }
                } else {
                    j.tanggal_display = 'Tanggal Belum Ditentukan';
                }

                // 2. Waktu Pelaksanaan Display
                if (dinamisObj.pukul && dinamisObj.pukul.trim() !== '') {
                    j.waktu_display = dinamisObj.pukul.trim();
                } else if (dinamisObj.waktu_ujian && dinamisObj.waktu_ujian.trim() !== '') {
                    j.waktu_display = dinamisObj.waktu_ujian.trim();
                } else if (j.jam_mulai) {
                    j.waktu_display = `${j.jam_mulai} - ${j.jam_selesai || 'Selesai'} WITA`;
                } else {
                    j.waktu_display = '09:00 - 11:00 WITA';
                }

                // 3. Ruangan / Tempat Display
                if (dinamisObj.bertempat_di && dinamisObj.bertempat_di.trim() !== '') {
                    j.ruangan_display = dinamisObj.bertempat_di.trim();
                } else if (dinamisObj.ruang_ujian && dinamisObj.ruang_ujian.trim() !== '') {
                    j.ruangan_display = dinamisObj.ruang_ujian.trim();
                } else if (dinamisObj.ruangan && dinamisObj.ruangan.trim() !== '') {
                    j.ruangan_display = dinamisObj.ruangan.trim();
                } else if (j.ruangan) {
                    j.ruangan_display = j.ruangan;
                } else {
                    j.ruangan_display = 'Ruang Ujian & Seminar TI';
                }
            }

            // Deduplicate schedules (hapus jadwal double)
            const uniqueMap = new Map();
            (listJadwal || []).forEach(j => {
                const key = `${j.mahasiswa_id}_${j.jenis_ujian}_${j.tanggal_display || j.tanggal_ujian}`;
                if (!uniqueMap.has(key) || uniqueMap.get(key).id < j.id) {
                    uniqueMap.set(key, j);
                }
            });
            listJadwal = Array.from(uniqueMap.values());

            // Filter berdasarkan tanggal jika parameter filter_tanggal diisi
            if (filter_tanggal && filter_tanggal.trim() !== '') {
                listJadwal = listJadwal.filter(j => j.tanggal_ujian === filter_tanggal.trim() || (j.tanggal_display && j.tanggal_display.includes(filter_tanggal.trim())));
            }

            // Sort berdasarkan tanggal_ujian ASC, jam_mulai ASC
            listJadwal.sort((a, b) => {
                const dateA = new Date(`${a.tanggal_ujian}T${a.jam_mulai || '00:00'}`);
                const dateB = new Date(`${b.tanggal_ujian}T${b.jam_mulai || '00:00'}`);
                return dateA - dateB;
            });

            return res.render('mahasiswa/jadwal_ujian', {
                title: user && user.role === 'dosen' ? 'Jadwal Ujian Mahasiswa Bimbingan & Pengujian' : 'Jadwal Ujian & Seminar TA',
                user: req.session.user,
                mhs,
                listJadwal,
                selectedTanggal: filter_tanggal || ''
            });
        } catch (err) {
            console.error('RenderJadwalUjian error:', err);
            return res.status(500).send('Internal Server Error: ' + err.message);
        }
    }

    static async deleteSurat(req, res) {
        try {
            const user = req.session.user;
            const mhs = await MahasiswaModel.findByUserId(user.id);
            if (!mhs) {
                return res.status(400).send('Profil mahasiswa tidak valid.');
            }

            const suratId = req.params.id;
            const pengajuan = await SuratModel.getDetailById(suratId);

            if (!pengajuan) {
                return res.redirect('/mahasiswa/daftar-surat?error=' + encodeURIComponent('Pengajuan surat tidak ditemukan.'));
            }

            if (parseInt(pengajuan.mahasiswa_id, 10) !== parseInt(mhs.id, 10)) {
                return res.redirect('/mahasiswa/daftar-surat?error=' + encodeURIComponent('Anda tidak memiliki akses untuk menghapus surat ini.'));
            }

            await db.run('DELETE FROM riwayat_disposisi WHERE pengajuan_surat_id = ?', [suratId]);
            await db.run('DELETE FROM pengajuan_surat WHERE id = ?', [suratId]);

            return res.redirect('/mahasiswa/daftar-surat?success=' + encodeURIComponent(`Permohonan surat "${pengajuan.perihal || pengajuan.nama_surat || 'Surat'}" berhasil dihapus.`));
        } catch (err) {
            console.error('Delete surat error:', err);
            return res.redirect('/mahasiswa/daftar-surat?error=' + encodeURIComponent('Gagal menghapus surat: ' + err.message));
        }
    }
}

module.exports = MahasiswaController;
